apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentConfig.name }}_api
spec:
  selector:
    app: {{ .Values.deploymentConfig.name }}_api
  ports:
    - name: apiport
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  type: {{ .Values.service.type }}
