apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends_api
  template:
    metadata:
      labels:
        app: techtrends_api
    spec:
      containers:
        - name: techtrends
          image: dsdatsme/techtrends:latest
          ports:
          - containerPort: 3111
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3111
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3111
