apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends_api
spec:
  selector:
    app: techtrends_api
  ports:
    - name: apiport
      port: 4111
      targetPort: 3111
      protocol: TCP
  type: ClusterIP
